<?php
define(POOLSIM_ROOT_DIR, ROOT_DIR . '/work');
define(POOLSIM_CONF_DIR, POOLSIM_ROOT_DIR . '/conf');
define(POOLSIM_LOG_DIR, POOLSIM_ROOT_DIR . '/log');
define(POOLSIM_BIN_DIR, POOLSIM_ROOT_DIR . '/bin');

define(POOLSIM_DAEMON_CONF_DIR, POOLSIM_ROOT_DIR . '/daemon');

define(POOLSIM_PROCESS_PATH, POOLSIM_BIN_DIR . '/poolsim');
define(POOLSIM_CONNECTION_LOOKUP, POOLSIM_BIN_DIR . '/connections');
